"""Oracle for the `## Documents in this repo` index that `README.md` publishes.

WHY THIS EXISTS
The vision's definition of done is that the register is the reference a builder checks
before starting an agent-infrastructure project, and that reference failed at the first
hop: `git ls-files '*.md'` named six documents and `README.md` named none of the other
five. The expensive shape was not the missing list, it was WHERE the omission fell.
`README.md`'s quickstart hands a reader `radar scan ... --json` "for a CI gate", and the
object that invocation emits is specified only in `docs/CONSUMER_CONTRACT.md` -- read by
several `src/` modules, a tool and many test modules, and named by no user-facing surface
at all. A reader was pointed at a payload whose contract was unreachable.

WHY THE EXPECTATION IS DERIVED FROM `git ls-files`, AND WHAT THAT COMMITS US TO
A hand-written list of documents in a test is the same artifact as the missing list in
the README, one directory over: it drifts the same way, and it would have to be edited by
the same person who forgot the document. So the expectation is the TRACKED Markdown set,
read through the seam `tools/check_public_safety.py` already settled for the same reason
(a directory walk sees build output, virtual environments and gitignored scratch).

THE DECISION THAT FOLLOWS, STATED SO A LATER ITERATION DOES NOT "FIX" IT: when a roadmap
row eventually adds another tracked Markdown document, this brake goes RED until that
document gets a README row. That is the brake working as designed. The repair is a row in
the README, never a hard-coded list here -- hard-coding the set would silently retire the
only property this module exists to hold.

WHY THE COMPARISON IS BOTH-DIRECTIONAL
The live drift was one-directional OMISSION, so a containment check ("every named path is
tracked") passes the pre-change README exactly as it stood -- it named no paths at all --
and proves nothing. Both directions are therefore checked: `unnamed_documents()` catches a
tracked document with no row, `unknown_paths()` catches a row naming a path git does not
track, and `unresolved_paths()` catches a name that resolves nowhere on disk.

WHY THE FUNCTIONS ARE PURE OVER `(readme_text, tracked_paths)`
The committed README can only ever demonstrate the PASSING side, so every rule here has to
be drivable from synthetic input to be proved two-sided at all. Passing the text and the
tracked set in as arguments is what makes a known-bad fixture a string in memory instead of
an edit to a file on disk that has to be put back. `unresolved_paths()` takes the existence
predicate for the same reason: a tracked path that was deleted but not committed is the one
case where "tracked" and "on disk" disagree, and it is not reachable by editing text.

WHY THE READERS FAIL CLOSED
Two inputs would otherwise turn every comparison below into two empty sets agreeing with
each other: a tracked set with no Markdown in it, and a README with no index heading. Both
raise. An empty expectation set is the green that means nothing, and this product has ruled
against that vacuous success on three other surfaces already.

WHY A ROW IS FOUND BY PATH TOKEN AND NOT BY SUBSTRING
`docs/CONSUMER_CONTRACT.md` contains `CONSUMER_CONTRACT.md`, so a substring search would let
a row naming the bare basename satisfy an expectation about the repo-relative path -- the
exact fail-open the index exists to close, since a bare basename is not a path a reader can
open from the repo root. Rows are matched against the path TOKENS a line contains.
"""

from __future__ import annotations

import pathlib
import re
import sys
from collections.abc import Callable, Iterable

#: Repo root found relative to this file, so no absolute machine path appears here and the
#: oracle reads the repo's own documents under `pytest -n auto` whatever a worker's cwd is.
REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
README_PATH = REPO_ROOT / "README.md"

_TOOLS_DIR = str(REPO_ROOT / "tools")
if _TOOLS_DIR not in sys.path:  # idempotent: the module may be imported by several tests
    sys.path.insert(0, _TOOLS_DIR)

import check_public_safety as _public_safety  # noqa: E402  (path set immediately above)

#: The one heading whose section this module treats as the published index.
INDEX_HEADING = "## Documents in this repo"

#: The closed provenance vocabulary. Two values, because the only question a contributor
#: needs answered before typing is whether a hand edit survives the next loop pass. A third
#: value would be a judgement call, and free text here is what turns an index into prose.
PROVENANCE_WORDS: tuple[str, ...] = ("generated by the build loop", "hand-maintained")

#: Documents whose provenance is NOT a free choice, and the reason it is pinned: this file's
#: committed head is a build-loop artifact, so a contributor who hand-edits it loses the
#: edit. Getting this row wrong is the one error in the index that costs a reader work.
PINNED_PROVENANCE: dict[str, str] = {"DIRECTIONS.md": "generated by the build loop"}

#: The README document itself, which owes no row in its own index.
_SELF = "README.md"

#: A repo-relative Markdown path: optional `dir/` segments, then `NAME.md`. Deliberately
#: refuses a bare `.md` and a glob (`*.md`), so prose ABOUT Markdown files is not read as a
#: claim about one -- the same fail-open as crediting a flag named in a Promise cell.
_MD_PATH = re.compile(r"(?:[A-Za-z0-9_.-]+/)*[A-Za-z0-9_-][A-Za-z0-9_.-]*\.md\b")

#: A heading that ENDS the index section. `### ` does not match, so a subheading stays
#: inside the section -- the same reading `test_iter23` already uses for a README section.
_SECTION_END = "## "


class DocumentIndexError(Exception):
    """The index could not be READ at all, so no verdict about it is available.

    Distinct from a violation on purpose. A violation is a difference between two sets that
    were both understood; this is an input whose shape defeats the question -- a missing or
    duplicated heading, or a tracked set with no Markdown in it. Raising rather than
    returning an empty list keeps an unanswerable question from being indistinguishable
    from a document with nothing wrong.
    """


def readme_text() -> str:
    """The committed README, decoded.

    A separate function so a caller can mutate the returned string in memory to build a
    known-bad, instead of editing the file on disk and having to put it back.
    """
    return README_PATH.read_text(encoding="utf-8")


def tracked_markdown(root: pathlib.Path | None = None) -> tuple[str, ...]:
    """Every tracked Markdown path, repo-relative and sorted.

    Reuses `check_public_safety.tracked_files()` rather than shelling to git again: a second
    opinion about what "tracked" means is the duplicated invariant this product has already
    paid to remove, and that function already fails loudly when git refuses.
    """
    root = REPO_ROOT if root is None else root
    return tuple(sorted(p for p in _public_safety.tracked_files(root) if p.endswith(".md")))


def expected_documents(tracked_paths: Iterable[str]) -> tuple[str, ...]:
    """The documents the index owes a row: tracked Markdown, minus the README itself.

    Fails closed on an empty result. An index whose expectation set is empty reports
    agreement between two empty sets, which is the green that means nothing -- and the
    caller cannot distinguish it from a correct index without this refusal.
    """
    documents = tuple(sorted({p for p in tracked_paths if p.endswith(".md") and p != _SELF}))
    if not documents:
        raise DocumentIndexError(
            "the tracked set names no Markdown document other than "
            f"{_SELF!r}, so there is nothing for the index to owe; refusing to "
            "report agreement between two empty sets")
    return documents


def index_section(text: str) -> str:
    """The index section's body: everything after its heading, up to the next `## `.

    The heading must occur EXACTLY ONCE. A reader keyed on a heading string cannot otherwise
    see document-level duplication: a second index section would leave one of them entirely
    unexamined while every assertion downstream passed.
    """
    lines = text.splitlines()
    at = [i for i, line in enumerate(lines) if line.strip() == INDEX_HEADING]
    if len(at) != 1:
        raise DocumentIndexError(
            f"heading {INDEX_HEADING!r} occurs {len(at)} time(s) in the document, "
            "expected exactly 1")
    body: list[str] = []
    for line in lines[at[0] + 1:]:
        if line.startswith(_SECTION_END):
            break
        body.append(line)
    return "\n".join(body)


def markdown_paths(text: str) -> tuple[str, ...]:
    """Every Markdown path `text` names, de-duplicated, in first-appearance order.

    Order is first-appearance rather than sorted so a message can point a reader at the
    document in the order they would meet it; de-duplication keeps one path named twice
    from reading as two findings.
    """
    seen: dict[str, None] = {}
    for match in _MD_PATH.finditer(text):
        seen.setdefault(match.group(0), None)
    return tuple(seen)


def unnamed_documents(text: str, tracked_paths: Iterable[str]) -> list[str]:
    """Tracked documents the index section does not name, sorted.

    Scoped to the SECTION, not the whole document: a path mentioned in passing elsewhere in
    the README is not an index row, and crediting it would let the index stay empty forever.
    """
    named = set(markdown_paths(index_section(text)))
    return [document for document in expected_documents(tracked_paths) if document not in named]


def unknown_paths(text: str, tracked_paths: Iterable[str]) -> list[str]:
    """Markdown paths named ANYWHERE in `text` that git does not track.

    Whole-document scope on purpose: a stale path in prose misleads a reader exactly as much
    as a stale row, and this is the direction the pre-change README could never exercise.
    """
    tracked = set(tracked_paths)
    return [path for path in markdown_paths(text) if path not in tracked]


def unresolved_paths(text: str, exists: Callable[[str], bool]) -> list[str]:
    """Markdown paths named in `text` for which `exists` answers False.

    The predicate is injected because the disagreement this catches -- a path that is
    tracked but no longer on disk -- cannot be produced by editing text, so a rule that
    called `Path.is_file()` itself could never be shown to fire.
    """
    return [path for path in markdown_paths(text) if not exists(path)]


def provenance_violations(text: str, tracked_paths: Iterable[str]) -> list[str]:
    """Every index row whose provenance is missing, ambiguous, or wrong.

    Three separate messages rather than one, because they call for different repairs: a row
    that does not exist is an omission, a row naming neither or both vocabulary values is a
    row a reader cannot act on, and a row disagreeing with `PINNED_PROVENANCE` states the
    one thing the column exists to say and states it falsely.
    """
    section = index_section(text)
    rows = section.splitlines()
    violations: list[str] = []
    for document in expected_documents(tracked_paths):
        matching = [row for row in rows if document in markdown_paths(row)]
        if len(matching) != 1:
            violations.append(
                f"{document}: named in {len(matching)} line(s) of the index, expected "
                "exactly 1")
            continue
        words = [word for word in PROVENANCE_WORDS if word in matching[0]]
        if len(words) != 1:
            violations.append(
                f"{document}: its row names {len(words)} provenance value(s) "
                f"{words}, expected exactly 1 of {list(PROVENANCE_WORDS)}")
            continue
        pinned = PINNED_PROVENANCE.get(document)
        if pinned is not None and words[0] != pinned:
            violations.append(
                f"{document}: its row says {words[0]!r}, but this document is {pinned!r}")
    return violations


def index_violations(text: str, tracked_paths: Iterable[str]) -> list[str]:
    """Every difference between the published index and the tracked Markdown set.

    One call site for the three text-only rules, so a caller asserting "the index is
    correct" cannot accidentally assert only the direction that was easy to check. The disk
    half stays separate: it needs a predicate, and a caller that has none should not be
    handed a silently weaker check under the same name.
    """
    documents = expected_documents(tracked_paths)  # fails closed before anything is read
    index_section(text)  # fails closed on a missing or duplicated heading
    violations = [f"{document}: tracked, but the index names no row for it"
                  for document in unnamed_documents(text, documents)]
    violations += [f"{path}: named in the README, but git does not track it"
                   for path in unknown_paths(text, tracked_paths)]
    violations += provenance_violations(text, documents)
    return violations
