"""Iteration 95 -- `README.md` publishes an index of every other tracked Markdown document.

WHAT THIS ITERATION CLAIMS, IN BEHAVIOURAL TERMS
`README.md` grows one section, `## Documents in this repo`, naming every other document in
`git ls-files '*.md'` by its repo-relative path with a provenance word each, and a committed
brake holds that index BOTH ways: nothing tracked goes unnamed, and no named path is untracked
or missing from disk. Nothing under `src/agent_gap_radar/` moves, so no renderer, exit code,
payload or verb surface may shift.

THE DECISION THIS MODULE RECORDS, STATED SO A LATER ITERATION DOES NOT "FIX" IT
The expectation set is DERIVED from `git ls-files`, never written down here. The consequence is
deliberate and is the whole point: when roadmap rows 64/70 eventually add `PRODUCT_ARCHIVE.md`
to the tracked set, this brake goes RED until that document gets a README row. That is the
brake working as designed, not a defect. The repair is a row in `README.md`; it is NEVER a
hard-coded list in this file, because a hard-coded list is the same artifact as the missing
README list one directory over -- it drifts the same way, and the person who would have to
update it is the person who just forgot the document.

WHY THE TWO-SIDED PROOFS ARE SYNTHETIC RATHER THAN FILE EDITS
The committed README can only ever demonstrate the PASSING side of every rule here. The rules
are therefore driven as pure functions over `(readme_text, tracked_paths)`, so a known-bad is a
string in memory instead of an edit to a tracked file that has to be put back -- and a failed
assertion cannot leave the repository dirty. One test proves that purity directly, by handing
the readers a tracked set of paths that exist nowhere on disk and requiring a clean verdict:
a reader that secretly consulted the filesystem would report those paths unresolvable.

WHAT THIS MODULE DELIBERATELY DOES NOT ASSERT
No line number, no column order, no table syntax and no wording: the index may be a table, a
list or prose, in any order, so long as each document is named by its repo-relative path with
exactly one provenance value. Two claims from the spec's acceptance criteria are NOT pinned
here and are named in `tester.md` as final-gate work, because both are assertions about SOURCE
TEXT that this station's isolation contract forbids it to read: "`git diff --stat` shows zero
lines changed under `src/agent_gap_radar/`", and the byte-for-byte comparison of renderer
stdout against its PRE-change bytes (a baseline that no longer exists once the diff is
applied). The behavioural consequence of both IS pinned, the way `test_iter30_behavior.py`
already settled for this repo: the renderers are shown to be INDEPENDENT of README content, by
running them against a register whose neighbouring README is mutated and requiring byte
equality -- a property that is testable on either branch, unlike equality with a vanished
baseline.

ISOLATION. Reads `README.md`, the tracked-file seam through `tests/_document_index.py`, and the
public CLI by RUNNING it. No network, no absolute machine path, no read of `src/`.
"""

from __future__ import annotations

import pathlib
import re
import shutil

import pytest

from agent_gap_radar.cli import main

import _document_index as index
from _document_index import (
    DocumentIndexError,
    INDEX_HEADING,
    PINNED_PROVENANCE,
    PROVENANCE_WORDS,
)

REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
README_PATH = REPO_ROOT / "README.md"
LIVE_GAPS = REPO_ROOT / "gaps"

#: The README document itself owes no row in its own index.
SELF = "README.md"

#: Behaviour 4's closed vocabulary, spelled here as the SPEC states it so a silent widening
#: of the oracle's tuple cannot pass unnoticed. Two values: the only question a contributor
#: needs answered before typing is whether a hand edit survives the next loop pass.
SPEC_PROVENANCE_WORDS = ("hand-maintained", "generated by the build loop")

#: Behaviour 4's one pinned row. `DIRECTIONS.md` is a build-loop artifact, so a contributor
#: who hand-edits it loses the edit -- the one error in this index that costs a reader work.
SPEC_PINNED = ("DIRECTIONS.md", "generated by the build loop")

#: Behaviour 7. Sentence splitting matches the convention `test_readme_confidence_rule.py`
#: already settled for this document, which is authored one paragraph per line.
_SENTENCE_END = re.compile(r"(?<=[.!?])\s+")
_CORROBORATION = re.compile(r"adds? a point|corroborat", re.I)
_ADDS_A_POINT = re.compile(r"adds? a point|adds? one point", re.I)

#: Behaviour 5's untracked path, chosen so it can never resolve: `docs/` exists, `NOPE.md`
#: does not, so the fixture exercises the untracked direction without also being unreadable.
UNTRACKED_PATH = "docs/NOPE.md"

#: Behaviour 8. The three verbs the spec requires to be unmoved. `taxonomy` takes no path at
#: all, which is why it is the control: it cannot depend on any document by construction.
RENDER_VERBS = ("report", "list", "taxonomy")


def _readme() -> str:
    return index.readme_text()


def _tracked() -> tuple[str, ...]:
    return index.tracked_markdown()


def _synthetic_index(documents, provenance="hand-maintained", extra_lines=(),
                     respect_pins=True):
    """A minimal README carrying one index row per document, plus any `extra_lines`.

    Deliberately NOT a copy of the committed file: a fixture built from the real document
    would pass for reasons the real document supplies, and this one has exactly the shape the
    readers are specified over -- a heading, some rows, and a following `## ` heading proving
    the section boundary is honoured.

    `respect_pins` gives every pinned document its correct provenance, so a fixture built to
    exercise ONE rule cannot also trip the provenance rule and make a one-violation assertion
    fail for an unrelated reason. Set it False to build a known-bad for the pin itself. That
    parameter exists because the first version of this helper did trip exactly that way: the
    oracle refused a synthetic index marking `DIRECTIONS.md` hand-maintained, which is the
    fail-closed behaviour working, on the fixture rather than on the product.
    """
    def row_provenance(document):
        if respect_pins and document in PINNED_PROVENANCE:
            return PINNED_PROVENANCE[document]
        return provenance

    rows = [f"| `{document}` | what it is | {row_provenance(document)} |"
            for document in documents]
    return "\n".join([
        "# synthetic",
        "",
        INDEX_HEADING,
        "",
        "| Document | What it is | Provenance |",
        "|---|---|---|",
        *rows,
        *extra_lines,
        "",
        "## Something after the section",
        "",
        "tail prose that is outside the index",
        "",
    ])


@pytest.fixture(scope="module")
def register_copy(tmp_path_factory):
    """A copy of the live register with NO neighbouring README, plus the same tree once a
    bogus README has been written beside it. Copied once for the module: the renderers are
    read-only, so successive runs cannot disturb each other.
    """
    root = tmp_path_factory.mktemp("register_copy")
    shutil.copytree(LIVE_GAPS, root / "gaps")
    return root


# --------------------------------------------------------------------------------------
# premise guards -- an empty domain would make every assertion below vacuously true
# --------------------------------------------------------------------------------------

def test_premise_the_repo_is_a_git_target_naming_several_markdown_documents():
    tracked = _tracked()
    assert tracked, "premise: git ls-files must name tracked Markdown files"
    assert SELF in tracked, f"premise: {SELF} must itself be tracked"
    documents = index.expected_documents(tracked)
    assert len(documents) >= 2, (
        f"premise: the index must owe rows for at least two documents, got {documents}")
    assert SELF not in documents, "the README owes no row in its own index"


# --------------------------------------------------------------------------------------
# Behavior 1 -- the heading exists exactly once
# --------------------------------------------------------------------------------------

def test_b1_the_index_heading_occurs_exactly_once_in_the_readme():
    stripped = [line.strip() for line in _readme().splitlines()]
    assert stripped.count(INDEX_HEADING) == 1, (
        f"expected exactly one line whose stripped form is {INDEX_HEADING!r}, "
        f"found {stripped.count(INDEX_HEADING)}")


def test_b1_the_heading_string_is_exactly_the_one_the_spec_names():
    assert INDEX_HEADING == "## Documents in this repo"


def test_b1_a_second_index_heading_is_refused_rather_than_half_read():
    """Two sections is the shape a heading-keyed reader cannot see: one of them would go
    entirely unexamined while every assertion downstream passed."""
    doubled = _readme() + f"\n{INDEX_HEADING}\n\nan impostor section\n"
    with pytest.raises(DocumentIndexError) as excinfo:
        index.index_section(doubled)
    assert "2 time(s)" in str(excinfo.value)


# --------------------------------------------------------------------------------------
# Behavior 2 -- every tracked document is named INSIDE the section, by exact path
# --------------------------------------------------------------------------------------

def test_b2_the_committed_index_names_every_other_tracked_document():
    tracked = _tracked()
    assert index.unnamed_documents(_readme(), tracked) == []


@pytest.mark.parametrize("document", index.expected_documents(index.tracked_markdown()))
def test_b2_each_tracked_document_appears_as_its_exact_repo_relative_path(document):
    section = index.index_section(_readme())
    assert document in index.markdown_paths(section), (
        f"{document} is not named in the index section as a repo-relative path token")


def test_b2_a_bare_basename_does_not_satisfy_a_nested_path():
    """`docs/CONSUMER_CONTRACT.md` CONTAINS `CONSUMER_CONTRACT.md`, so a substring reading
    would credit a row a reader cannot open from the repo root. Proved on the real nested
    documents rather than on an invented one."""
    tracked = _tracked()
    nested = [p for p in index.expected_documents(tracked) if "/" in p]
    assert nested, "premise: at least one tracked document must live in a subdirectory"
    for document in nested:
        basename_only = _synthetic_index([document.rsplit("/", 1)[1]])
        missing = index.unnamed_documents(basename_only, (SELF, document))
        assert missing == [document], (
            f"a row naming only {document.rsplit('/', 1)[1]!r} must leave {document} unnamed, "
            f"got {missing}")


def test_b2_naming_a_document_outside_the_section_does_not_count():
    """Scoped to the SECTION on purpose: a path mentioned in passing elsewhere is not an
    index row, and crediting it would let the index stay empty forever."""
    tracked = (SELF, "VISION.md")
    outside = "\n".join([
        "# synthetic",
        "",
        "prose naming VISION.md well before any index",
        "",
        INDEX_HEADING,
        "",
        "an index with no rows at all",
        "",
    ])
    assert index.unnamed_documents(outside, tracked) == ["VISION.md"]


# --------------------------------------------------------------------------------------
# Behavior 3 -- every Markdown path named anywhere in the README is tracked AND on disk
# --------------------------------------------------------------------------------------

def test_b3_every_markdown_path_named_in_the_readme_is_tracked():
    assert index.unknown_paths(_readme(), _tracked()) == []


def test_b3_every_markdown_path_named_in_the_readme_resolves_on_disk():
    def exists(path: str) -> bool:
        return (REPO_ROOT / path).is_file()

    assert index.unresolved_paths(_readme(), exists) == []


def test_b3_the_direction_is_no_longer_vacuous():
    """Before this iteration `README.md` contained the substring `.md` zero times, so
    "every named path is tracked" passed by naming nothing. Anti-vacuity: it must now name
    at least as many paths as the index owes rows."""
    named = index.markdown_paths(_readme())
    owed = index.expected_documents(_tracked())
    assert len(named) >= len(owed), (
        f"the README names {len(named)} Markdown path(s) but owes {len(owed)} rows")


def test_b3_a_glob_or_a_bare_extension_is_not_read_as_a_path():
    """Prose ABOUT Markdown files must not be read as a claim about one, or documenting the
    brake would red it."""
    for text in ("every *.md file", "a bare .md suffix", "the `*.md` set"):
        assert index.markdown_paths(text) == (), f"{text!r} must name no path"


# --------------------------------------------------------------------------------------
# Behavior 4 -- provenance from a closed two-value vocabulary, DIRECTIONS.md pinned
# --------------------------------------------------------------------------------------

def test_b4_the_committed_index_has_no_provenance_violation():
    assert index.provenance_violations(_readme(), _tracked()) == []


def test_b4_the_vocabulary_is_the_closed_two_value_set_the_spec_names():
    assert sorted(PROVENANCE_WORDS) == sorted(SPEC_PROVENANCE_WORDS)


def test_b4_directions_md_is_marked_generated_by_the_build_loop():
    document, provenance = SPEC_PINNED
    assert PINNED_PROVENANCE.get(document) == provenance
    section = index.index_section(_readme())
    rows = [row for row in section.splitlines() if document in index.markdown_paths(row)]
    assert len(rows) == 1, f"expected exactly one {document} row, found {len(rows)}"
    assert provenance in rows[0], (
        f"{document} is a build-loop artifact, so its row must say {provenance!r}: {rows[0]!r}")


def test_b4_a_wrong_provenance_on_the_pinned_document_is_a_violation():
    document, provenance = SPEC_PINNED
    wrong = _synthetic_index([document], provenance="hand-maintained", respect_pins=False)
    violations = index.provenance_violations(wrong, (SELF, document))
    assert len(violations) == 1 and document in violations[0], violations
    assert provenance in violations[0], (
        f"the message must name the correct provenance {provenance!r}: {violations}")


def test_b4_a_row_naming_no_provenance_value_is_a_violation():
    text = _synthetic_index(["VISION.md"], provenance="who knows")
    violations = index.provenance_violations(text, (SELF, "VISION.md"))
    assert len(violations) == 1 and "0 provenance value(s)" in violations[0], violations


def test_b4_a_row_naming_both_provenance_values_is_a_violation():
    text = _synthetic_index(
        ["VISION.md"], provenance="hand-maintained and generated by the build loop")
    violations = index.provenance_violations(text, (SELF, "VISION.md"))
    assert len(violations) == 1 and "2 provenance value(s)" in violations[0], violations


def test_b4_a_document_named_in_two_rows_is_a_violation():
    text = _synthetic_index(["VISION.md", "VISION.md"])
    violations = index.provenance_violations(text, (SELF, "VISION.md"))
    assert len(violations) == 1 and "2 line(s)" in violations[0], violations


# --------------------------------------------------------------------------------------
# Behavior 5 -- pure functions over (readme_text, tracked_paths), proved TWO-SIDED
# --------------------------------------------------------------------------------------

def test_b5_the_committed_readme_yields_no_index_violation():
    """The passing side, which is the only side the committed file can ever show."""
    assert index.index_violations(_readme(), _tracked()) == []


@pytest.mark.parametrize("omitted", index.expected_documents(index.tracked_markdown()))
def test_b5_a_readme_omitting_one_tracked_document_names_that_document(omitted):
    """The spec requires "a violation naming that document", and the COUNT is deliberately
    not pinned: the aggregate currently reports an omission twice, once as a missing row and
    once as a row naming the document zero times. Both name the omitted document and both
    call for the same repair, so requiring exactly one would pin a redundancy a later
    iteration might reasonably remove. What IS pinned is that no OTHER document is dragged
    into the report -- collateral noise is what makes a violation list unreadable.
    """
    tracked = _tracked()
    kept = [d for d in index.expected_documents(tracked) if d != omitted]
    text = _synthetic_index(kept)
    violations = index.index_violations(text, tracked)
    assert violations, f"omitting {omitted} must yield a violation"
    assert all(omitted in v for v in violations), (
        f"every violation must name {omitted}, got {violations}")
    assert any("the index names no row for it" in v for v in violations), violations


def test_b5_a_readme_naming_an_untracked_path_names_that_path():
    tracked = _tracked()
    documents = index.expected_documents(tracked)
    text = _synthetic_index([*documents, UNTRACKED_PATH])
    violations = index.index_violations(text, tracked)
    assert len(violations) == 1, f"expected exactly one violation, got {violations}"
    assert UNTRACKED_PATH in violations[0], violations
    assert "git does not track it" in violations[0], violations


def test_b5_a_readme_naming_exactly_the_tracked_set_yields_no_violation():
    tracked = _tracked()
    text = _synthetic_index(index.expected_documents(tracked))
    assert index.index_violations(text, tracked) == []


def test_b5_the_readers_are_pure_and_never_consult_the_filesystem():
    """Handed a tracked set of paths that exist NOWHERE on disk, a correct reader returns a
    clean verdict; a reader that secretly stat-ed the paths could not."""
    fictional = (SELF, "IMAGINARY.md", "nested/ALSO_IMAGINARY.md")
    text = _synthetic_index([p for p in fictional if p != SELF])
    for path in fictional:
        assert not (REPO_ROOT / path).exists() or path == SELF, (
            f"premise: {path} must not exist on disk")
    assert index.index_violations(text, fictional) == []


def test_b5_an_untracked_path_anywhere_in_the_document_is_caught_not_only_in_the_section():
    """Whole-document scope for this direction: a stale path in prose misleads a reader
    exactly as much as a stale row."""
    tracked = _tracked()
    documents = index.expected_documents(tracked)
    text = _synthetic_index(documents) + f"\n\nsee also `{UNTRACKED_PATH}` for details\n"
    violations = index.index_violations(text, tracked)
    assert [v for v in violations if UNTRACKED_PATH in v], violations


def test_b5_the_functions_take_the_tracked_set_as_an_argument():
    """A signature check, because the two-sided proofs above are only possible while the
    tracked set is injected rather than read inside each reader."""
    import inspect
    for func in (index.unnamed_documents, index.unknown_paths, index.index_violations,
                 index.provenance_violations, index.expected_documents):
        params = list(inspect.signature(func).parameters)
        assert "tracked_paths" in params, f"{func.__name__} must accept tracked_paths: {params}"
    assert list(inspect.signature(index.unresolved_paths).parameters) == ["text", "exists"]


# --------------------------------------------------------------------------------------
# Behavior 6 -- the readers FAIL CLOSED; an empty expectation set is the green that lies
# --------------------------------------------------------------------------------------

def test_b6_an_empty_tracked_set_raises_rather_than_reporting_no_violations():
    with pytest.raises(DocumentIndexError):
        index.expected_documents(())
    with pytest.raises(DocumentIndexError):
        index.index_violations(_readme(), ())


def test_b6_a_tracked_set_with_no_markdown_raises():
    """The realistic shape of the same fault: git answers, but nothing it names is Markdown."""
    with pytest.raises(DocumentIndexError):
        index.index_violations(_readme(), ("pyproject.toml", "LICENSE", "uv.lock"))


def test_b6_a_tracked_set_holding_only_the_readme_raises():
    with pytest.raises(DocumentIndexError) as excinfo:
        index.expected_documents((SELF,))
    assert "nothing for the index to owe" in str(excinfo.value)


def test_b6_a_readme_without_the_index_heading_raises():
    text = "# synthetic\n\nno index anywhere\n\n## Another section\n\nprose\n"
    with pytest.raises(DocumentIndexError) as excinfo:
        index.index_section(text)
    assert "0 time(s)" in str(excinfo.value)
    with pytest.raises(DocumentIndexError):
        index.index_violations(text, _tracked())
    with pytest.raises(DocumentIndexError):
        index.unnamed_documents(text, _tracked())


def test_b6_the_refusal_is_a_distinct_type_and_not_an_empty_result():
    """The distinction the failure mode needs: a violation is a difference between two sets
    that were both understood, a refusal is an input whose shape defeats the question."""
    assert issubclass(DocumentIndexError, Exception)
    assert not issubclass(DocumentIndexError, (AssertionError, SystemExit))


# --------------------------------------------------------------------------------------
# Behavior 7 -- the corroboration rule is still stated exactly once
# --------------------------------------------------------------------------------------

def test_b7_exactly_one_sentence_states_the_corroboration_rule():
    sentences = _SENTENCE_END.split(_readme())
    hits = [s for s in sentences if _CORROBORATION.search(s)]
    assert len(hits) == 1, (
        f"expected exactly 1 sentence matching {_CORROBORATION.pattern!r}, "
        f"found {len(hits)}: {hits}")


def test_b7_exactly_one_sentence_says_a_point_is_added():
    sentences = _SENTENCE_END.split(_readme())
    hits = [s for s in sentences if _ADDS_A_POINT.search(s)]
    assert len(hits) == 1, (
        f"expected exactly 1 sentence matching {_ADDS_A_POINT.pattern!r}, "
        f"found {len(hits)}: {hits}")


def test_b7_the_new_index_section_states_no_corroboration_rule():
    """Where a duplicate would have come from: the section is new prose in the same file the
    two committed brakes count over."""
    section = index.index_section(_readme())
    assert _CORROBORATION.search(section) is None, (
        f"the index section must add no corroboration sentence: {section!r}")
    assert _ADDS_A_POINT.search(section) is None


# --------------------------------------------------------------------------------------
# Behavior 8 -- documentation-only: the renderers cannot have moved
# --------------------------------------------------------------------------------------

@pytest.mark.parametrize("verb", RENDER_VERBS)
def test_b8_each_renderer_exits_zero_with_empty_stderr_and_one_trailing_newline(verb, capsys):
    argv = [verb] if verb == "taxonomy" else [verb, str(REPO_ROOT)]
    assert main(argv) == 0
    captured = capsys.readouterr()
    assert captured.err == "", f"{verb} wrote to stderr: {captured.err!r}"
    assert captured.out, f"{verb} wrote no document"
    assert captured.out.endswith("\n") and not captured.out.endswith("\n\n"), (
        f"{verb} must end in exactly one newline")


@pytest.mark.parametrize("verb", RENDER_VERBS)
def test_b8_each_renderer_is_byte_stable_across_two_runs(verb, capsys):
    argv = [verb] if verb == "taxonomy" else [verb, str(REPO_ROOT)]
    assert main(argv) == 0
    first = capsys.readouterr().out
    assert main(argv) == 0
    second = capsys.readouterr().out
    assert first == second, f"{verb} is not byte-stable across runs"


@pytest.mark.parametrize("verb", ("report", "list"))
def test_b8_renderer_bytes_are_independent_of_readme_content(verb, register_copy, capsys):
    """The testable half of "byte-identical to the pre-change bytes". Equality with a
    PRE-change baseline is not black-box reachable once the diff is applied, so the property
    behind it is asserted instead: a documentation change cannot move renderer output,
    because the renderer does not read documentation at all.
    """
    readme = register_copy / "README.md"
    if readme.exists():
        readme.unlink()
    assert main([verb, str(register_copy)]) == 0
    without = capsys.readouterr()
    assert without.err == ""

    readme.write_text(
        "# mutated\n\n## Documents in this repo\n\n| `NOTHING.md` | x | invented |\n",
        encoding="utf-8")
    assert main([verb, str(register_copy)]) == 0
    with_readme = capsys.readouterr()
    assert with_readme.err == ""
    assert with_readme.out == without.out, (
        f"{verb} output changed when a README appeared beside the register")
    readme.unlink()


def test_b8_the_live_register_and_a_copy_of_it_render_identically(register_copy, capsys):
    """Anti-vacuity for the test above: the copy must be a real register, not an empty
    directory that renders the same bytes whatever sits next to it."""
    assert main(["report", str(REPO_ROOT)]) == 0
    live = capsys.readouterr().out
    assert main(["report", str(register_copy)]) == 0
    copied = capsys.readouterr().out
    assert live == copied
    assert "GAP-" in live, "anti-vacuity: the rendered report must name records"


def test_b8_this_module_records_the_derived_expectation_decision():
    """The acceptance criterion that a later iteration must not "fix" by hard-coding the
    document list. Asserted rather than merely written, so removing it reds."""
    doc = __doc__ or ""
    assert "PRODUCT_ARCHIVE.md" in doc
    assert "hard-coded" in doc
    assert "git ls-files" in doc
    oracle_doc = index.__doc__ or ""
    assert "git ls-files" in oracle_doc
