"""Unit tests for the `_document_index` oracle: does the checker actually check?

These ask ONE question -- does each rule fire on a known-bad and stay silent on a known-good
-- and they never read the committed `README.md`, so they hold whatever state that document
is in. That separation is the point: the committed file can only ever demonstrate the
PASSING side of an index rule, so absence of a finding over it is evidence only once the
same function has been shown to produce one.

Every bad fixture is a MUTATION of the good one and asserts its own premise. A silently
no-op replace would turn a known-bad fixture into a copy of the known-good one, and the test
would then pass while measuring nothing -- the fail-open this product has already paid for
twice on other surfaces.
"""

from __future__ import annotations

import pytest

from _document_index import (
    DocumentIndexError,
    INDEX_HEADING,
    PINNED_PROVENANCE,
    PROVENANCE_WORDS,
    expected_documents,
    index_section,
    index_violations,
    markdown_paths,
    provenance_violations,
    unknown_paths,
    unnamed_documents,
    unresolved_paths,
)

#: A synthetic tracked set. Synthetic rather than the live one so a fixture cannot red this
#: file when a roadmap row legitimately adds a document to the repo.
TRACKED = ("README.md", "VISION.md", "docs/CONSUMER_CONTRACT.md", "DIRECTIONS.md")

GOOD = f"""# a repo

prose that names no document.

{INDEX_HEADING}

| Document | What it is | Provenance |
|---|---|---|
| `VISION.md` | the fixed intent | hand-maintained |
| `docs/CONSUMER_CONTRACT.md` | what a consumer may rely on | hand-maintained |
| `DIRECTIONS.md` | the loop's working notes | generated by the build loop |

## Something else

closing prose.
"""

VISION_ROW = "| `VISION.md` | the fixed intent | hand-maintained |\n"
DIRECTIONS_ROW = "| `DIRECTIONS.md` | the loop's working notes | generated by the build loop |"

OMITS_ONE = GOOD.replace(VISION_ROW, "")
NAMES_UNTRACKED = GOOD.replace(VISION_ROW, VISION_ROW + "| `docs/NOPE.md` | gone | hand-maintained |\n")
BARE_BASENAME = GOOD.replace("`docs/CONSUMER_CONTRACT.md`", "`CONSUMER_CONTRACT.md`")
NO_PROVENANCE = GOOD.replace(VISION_ROW, "| `VISION.md` | the fixed intent | who knows |\n")
BOTH_PROVENANCE = GOOD.replace(
    VISION_ROW, "| `VISION.md` | hand-maintained, or generated by the build loop | ? |\n")
WRONG_PINNED = GOOD.replace(DIRECTIONS_ROW,
                            "| `DIRECTIONS.md` | the loop's working notes | hand-maintained |")
NO_HEADING = GOOD.replace(INDEX_HEADING + "\n", "")
TWO_HEADINGS = GOOD.replace("## Something else", INDEX_HEADING)
OUTSIDE_SECTION = GOOD.replace(VISION_ROW, "").replace(
    "closing prose.", "closing prose about `VISION.md`.")
DUPLICATED_ROW = GOOD.replace(VISION_ROW, VISION_ROW + VISION_ROW)


def test_every_bad_fixture_really_is_a_mutation_of_the_good_one() -> None:
    """Premise for every control below; one no-op replace would void the test using it."""
    mutations = {
        "OMITS_ONE": OMITS_ONE, "NAMES_UNTRACKED": NAMES_UNTRACKED,
        "BARE_BASENAME": BARE_BASENAME, "NO_PROVENANCE": NO_PROVENANCE,
        "BOTH_PROVENANCE": BOTH_PROVENANCE, "WRONG_PINNED": WRONG_PINNED,
        "NO_HEADING": NO_HEADING, "TWO_HEADINGS": TWO_HEADINGS,
        "OUTSIDE_SECTION": OUTSIDE_SECTION, "DUPLICATED_ROW": DUPLICATED_ROW,
    }
    unchanged = sorted(name for name, text in mutations.items() if text == GOOD)
    assert unchanged == [], unchanged


# --------------------------------------------------------------------- the good side


def test_the_good_fixture_yields_no_violation_at_all() -> None:
    """Known-good: a correct index must not red a build, in any of the three rules."""
    assert index_violations(GOOD, TRACKED) == []


def test_the_good_fixture_names_every_expected_document_in_its_section() -> None:
    assert unnamed_documents(GOOD, TRACKED) == []
    assert unknown_paths(GOOD, TRACKED) == []
    assert provenance_violations(GOOD, TRACKED) == []


def test_expected_documents_excludes_the_readme_and_every_non_markdown_path() -> None:
    """The README owes no row in its own index, and the domain is Markdown only."""
    assert expected_documents(TRACKED + ("pyproject.toml", "src/x.py")) == (
        "DIRECTIONS.md", "VISION.md", "docs/CONSUMER_CONTRACT.md")


# --------------------------------------------------------- the bad side, rule by rule


def test_an_omitted_document_is_reported_by_name() -> None:
    """Behavior 5's first synthetic proof: the omission direction, which is the live one."""
    assert unnamed_documents(OMITS_ONE, TRACKED) == ["VISION.md"]
    assert any("VISION.md" in message for message in index_violations(OMITS_ONE, TRACKED))


def test_a_named_untracked_document_is_reported_by_path() -> None:
    """Behavior 5's second synthetic proof: the direction the committed file cannot exercise."""
    assert unknown_paths(NAMES_UNTRACKED, TRACKED) == ["docs/NOPE.md"]
    assert any("docs/NOPE.md" in message
               for message in index_violations(NAMES_UNTRACKED, TRACKED))


def test_a_bare_basename_does_not_satisfy_a_repo_relative_expectation() -> None:
    """The substring fail-open: `docs/CONSUMER_CONTRACT.md` CONTAINS its own basename, so a
    substring search would credit a row naming a path no reader can open from the root."""
    assert unnamed_documents(BARE_BASENAME, TRACKED) == ["docs/CONSUMER_CONTRACT.md"]
    assert unknown_paths(BARE_BASENAME, TRACKED) == ["CONSUMER_CONTRACT.md"]


def test_a_path_named_outside_the_section_is_not_an_index_row() -> None:
    """Scope control: crediting a passing mention would let the index stay empty forever."""
    assert "VISION.md" in markdown_paths(OUTSIDE_SECTION)
    assert unnamed_documents(OUTSIDE_SECTION, TRACKED) == ["VISION.md"]


def test_a_row_naming_neither_provenance_value_is_reported() -> None:
    violations = provenance_violations(NO_PROVENANCE, TRACKED)
    assert len(violations) == 1, violations
    assert "VISION.md" in violations[0] and "0 provenance value" in violations[0]


def test_a_row_naming_both_provenance_values_is_reported_as_ambiguous() -> None:
    """Both is not a pass. A reader cannot act on a row that answers the question twice."""
    violations = provenance_violations(BOTH_PROVENANCE, TRACKED)
    assert len(violations) == 1, violations
    assert "2 provenance value" in violations[0], violations[0]


def test_a_pinned_document_marked_hand_maintained_is_reported() -> None:
    """The one row whose value is not a free choice: a wrong answer here costs a reader an
    edit that the next loop pass silently discards."""
    violations = provenance_violations(WRONG_PINNED, TRACKED)
    assert len(violations) == 1, violations
    for fragment in ("DIRECTIONS.md", "hand-maintained", PINNED_PROVENANCE["DIRECTIONS.md"]):
        assert fragment in violations[0], (fragment, violations[0])


def test_one_document_named_by_two_rows_is_reported_rather_than_read_once() -> None:
    """Set membership cannot see duplication, and two rows for one document can disagree --
    one correct, one stale -- with every other assertion here still passing."""
    violations = provenance_violations(DUPLICATED_ROW, TRACKED)
    assert len(violations) == 1, violations
    assert "named in 2 line(s)" in violations[0], violations[0]


# ------------------------------------------------------------------- fail-closed paths


def test_a_tracked_set_with_no_sibling_markdown_raises_instead_of_reporting_health() -> None:
    """Behavior 6, first half: an empty expectation set is the green that means nothing."""
    for empty in ((), ("README.md",), ("pyproject.toml", "src/cli.py")):
        with pytest.raises(DocumentIndexError):
            expected_documents(empty)
        with pytest.raises(DocumentIndexError):
            index_violations(GOOD, empty)


def test_a_readme_without_the_index_heading_raises() -> None:
    """Behavior 6, second half: no heading is an unanswerable question, not a clean bill."""
    assert INDEX_HEADING not in NO_HEADING
    with pytest.raises(DocumentIndexError):
        index_section(NO_HEADING)
    with pytest.raises(DocumentIndexError):
        index_violations(NO_HEADING, TRACKED)


def test_a_duplicated_index_heading_raises() -> None:
    """Two sections would leave one of them wholly unexamined while every check passed."""
    assert TWO_HEADINGS.count(INDEX_HEADING) == 2
    with pytest.raises(DocumentIndexError):
        index_violations(TWO_HEADINGS, TRACKED)


# ------------------------------------------------------------- section and path reading


def test_the_section_ends_at_the_next_h2_and_not_before() -> None:
    section = index_section(GOOD)
    assert "`VISION.md`" in section
    assert "closing prose" not in section
    assert "## Something else" not in section


def test_an_h3_subheading_does_not_end_the_section() -> None:
    """`### ` is inside the section by the same reading an existing README section test uses,
    so a future sub-grouping of the index cannot silently hide half of its rows."""
    with_subheading = GOOD.replace(DIRECTIONS_ROW, "### loop-owned\n\n" + DIRECTIONS_ROW)
    assert with_subheading != GOOD
    assert "DIRECTIONS.md" in markdown_paths(index_section(with_subheading))
    assert unnamed_documents(with_subheading, TRACKED) == []


def test_prose_about_markdown_files_is_not_read_as_a_path() -> None:
    """Domain control. A glob or a bare extension is prose ABOUT documents; reading either
    as a path would report a violation about a file nobody claimed exists."""
    assert markdown_paths("every tracked *.md file, whose .md suffix is not a path") == ()


def test_paths_are_deduplicated_in_first_appearance_order() -> None:
    """Order is first-appearance so a message points a reader in reading order, and one path
    named twice reads as one finding rather than two."""
    assert markdown_paths("see `b.md`, then `a/c.md`, then `b.md` again") == ("b.md", "a/c.md")


def test_the_disk_half_fires_and_stays_silent_under_an_injected_predicate() -> None:
    """Two-sided over the one disagreement text cannot produce: tracked, but not on disk."""
    assert unresolved_paths(GOOD, lambda path: True) == []
    assert unresolved_paths(GOOD, lambda path: path != "VISION.md") == ["VISION.md"]


def test_the_provenance_vocabulary_is_closed_and_its_values_are_disjoint() -> None:
    """Neither value may contain the other: overlap would make a one-word row read as two,
    which is exactly the ambiguity the two-value check exists to report."""
    assert len(PROVENANCE_WORDS) == 2, PROVENANCE_WORDS
    first, second = PROVENANCE_WORDS
    assert first not in second and second not in first
    assert set(PINNED_PROVENANCE.values()) <= set(PROVENANCE_WORDS)
