"""Iteration 260 behaviors: the register ships as a committed, generated artifact plus a
two-sided drift door.

Black-box, and the ISOLATION CONTRACT IS HONORED: nothing here reads the implementation
source, the engineer's or the reviewer's notes, `IMPLEMENTATION.patch`, or any diff. Every
expectation is a clause of `pm.md`'s six numbered Expected Behaviors, measured either by
reading the ARTIFACT'S BYTES or by RUNNING `tools/check_register_doc.py` in a real
`subprocess`. The one sweep that looks at a source file (behavior 5's "neither number is
written down anywhere") COUNTS token occurrences in `tools/*.py` and never asserts on the
code around them -- the same `rg`-shaped sweep `test_iter248_*` and iteration 259's
behavior 6 already established.

Why a real child process for the door: behavior 3 is precisely a claim about the door's
EXIT CODE and its TWO byte channels from an arbitrary working directory. An in-process
call cannot observe an exit code, and an `io.StringIO` capture cannot observe a cwd. The
child is launched with `sys.executable` -- never a `python3` that may be a wrapper shim on
the developer's PATH, which would surface as a spurious `ModuleNotFoundError` for a
runtime dep and read exactly like the cwd defect behavior 3 forbids.

Structural notes, so a green dot cannot mean less than it looks like:

* **The door is proved TWO-SIDEDLY**, as the acceptance criteria demand. Green: the tree as
  committed, from three different working directories, one of which is POISONED with a
  wrong-bytes `REGISTER.md` so a door that resolved its root from the cwd would refuse
  there. Red: four mutated copies via `--file`, plus a control copy that is byte-identical
  and must stay silent, so the refusal is attributable to the DRIFT and not to the flag.
* **One mutation is length-preserving.** A single XOR'd byte in the middle keeps both byte
  counts equal, so it is the only arm that separates a real byte comparison from a cheap
  length comparison. The appended-newline arm is the spec's own example.
* **No byte count is written down here either.** Every expected number is derived at run
  time from the artifact on disk, so this module cannot re-baseline the document and cannot
  go stale when the register grows. Iteration 259 recorded that transcribing a literal
  instead of extracting it mechanically is this seat's most expensive self-inflicted red.
* **Cost is bounded by construction** (`pm.md`'s `stage-budget: WARN` -- this seat sits at
  the 600 s cap). One in-process render, cached module-wide; ten short subprocess runs, each
  cached in a module-scoped fixture so no arm pays twice; no `radar scan`, no `copytree` of
  the 120-record register, no timing.
* **No absolute machine path and no personal identifier appears here.** The repo is located
  relative to `__file__`; every mutated copy lives under pytest's `tmp_path_factory`.
"""

from __future__ import annotations

import contextlib
import hashlib
import io
import pathlib
import re
import subprocess
import sys

import pytest

from agent_gap_radar.cli import main

#: Repo root, found relative to this file so no absolute machine path is written down.
REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]

#: Behavior 1's artifact and behavior 3-5's door, both named by `pm.md`.
ARTIFACT = REPO_ROOT / "REGISTER.md"
DOOR = REPO_ROOT / "tools" / "check_register_doc.py"
README = REPO_ROOT / "README.md"

#: The regeneration command behaviors 4 and 6 require VERBATIM. It is the published
#: command, so the artifact's provenance is reproducible by a reader with only the README.
REGEN_COMMAND = "uv run radar report . > REGISTER.md"

#: `pm.md` behavior 1: the artifact's bytes are the stdout of THIS argv, nothing else.
RENDER_ARGV = ("report", str(REPO_ROOT))

#: Behavior 1's "no added header, footer or provenance banner". Byte equality is the
#: primary proof; these phrases catch a banner that a renderer change had put in BOTH
#: sides, which equality alone would not notice.
BANNER_PHRASES = ("do not edit", "generated by", "auto-generated", "autogenerated")


def _run_door(*args, cwd):
    """Run the drift door as a real child process and return (rc, stdout, stderr) bytes."""
    proc = subprocess.run(
        [sys.executable, str(DOOR), *args],
        capture_output=True,
        cwd=str(cwd),
    )
    return proc.returncode, proc.stdout, proc.stderr


def _tracked(relative_path):
    """True when git already tracks (or has staged) `relative_path`."""
    proc = subprocess.run(
        ["git", "ls-files", "--error-unmatch", "--", relative_path],
        capture_output=True,
        cwd=str(REPO_ROOT),
    )
    return proc.returncode == 0


@pytest.fixture(scope="module")
def committed_bytes():
    """The artifact exactly as it sits in the tree, read as bytes (never decoded)."""
    return ARTIFACT.read_bytes()


@pytest.fixture(scope="module")
def rendered_bytes():
    """UTF-8 stdout of `main(["report", <repo root>])`, captured once for the module."""
    buffer = io.StringIO()
    with contextlib.redirect_stdout(buffer):
        rc = main(list(RENDER_ARGV))
    assert rc == 0, f"the render this artifact is a golden for exited {rc}, not 0"
    text = buffer.getvalue()
    assert text, "the renderer produced no stdout, so byte equality would be vacuous"
    return text.encode("utf-8")


@pytest.fixture(scope="module")
def green_arms(tmp_path_factory):
    """Behavior 3: the door with NO arguments, from three unrelated working directories.

    The third is poisoned -- it holds a `REGISTER.md` whose bytes are deliberately wrong --
    so a door that resolved the repo root (or the artifact) from the cwd refuses there.
    """
    neutral = tmp_path_factory.mktemp("neutral_cwd")
    poisoned = tmp_path_factory.mktemp("poisoned_cwd")
    (poisoned / "REGISTER.md").write_bytes(b"# not the register at all\n")
    return {
        "repo_root": (_run_door(cwd=REPO_ROOT), REPO_ROOT),
        "neutral_cwd": (_run_door(cwd=neutral), neutral),
        "poisoned_cwd": (_run_door(cwd=poisoned), poisoned),
    }


@pytest.fixture(scope="module")
def drift_arms(tmp_path_factory, committed_bytes):
    """Behaviors 4-5: four mutated copies plus one byte-identical control.

    `flipped_byte` is length-preserving on purpose: it is the only arm that distinguishes a
    byte comparison from a length comparison.
    """
    raw = committed_bytes
    flipped = bytearray(raw)
    midpoint = len(flipped) // 2
    flipped[midpoint] ^= 0x01

    mutations = {
        "appended_newline": raw + b"\n",
        "flipped_byte": bytes(flipped),
        "truncated": raw[: len(raw) // 2],
        "emptied": b"",
        "identical_control": raw,
    }

    directory = tmp_path_factory.mktemp("drift_copies")
    neutral = tmp_path_factory.mktemp("drift_cwd")
    arms = {}
    for name, data in mutations.items():
        copy = directory / f"{name}.md"
        copy.write_bytes(data)
        arms[name] = (_run_door("--file", str(copy), cwd=neutral), copy, data)
    return arms


def _sole_stderr_line(stderr, label):
    """Assert stderr is EXACTLY one newline-terminated line and return it as text."""
    assert stderr, f"{label}: stderr is empty, so the door refused silently"
    assert stderr.endswith(b"\n"), f"{label}: stderr does not end in a newline: {stderr!r}"
    body = stderr[:-1]
    assert b"\n" not in body, (
        f"{label}: stderr carries more than one line: {stderr!r}"
    )
    text = stderr.decode("utf-8")
    assert text.startswith("Error: "), f"{label}: stderr does not start with 'Error: ': {text!r}"
    return text.rstrip("\n")


# --------------------------------------------------------------------------------------
# Behavior 1 -- the artifact exists, is tracked, is non-empty, and IS the render's bytes.
# --------------------------------------------------------------------------------------


def test_b1_the_artifact_exists_at_the_repo_root_and_is_tracked(committed_bytes):
    assert ARTIFACT.is_file(), "REGISTER.md is not a file at the repo root"
    assert committed_bytes, "REGISTER.md is empty"
    assert _tracked("REGISTER.md"), "REGISTER.md is not tracked by git"


def test_b1_the_artifact_is_byte_for_byte_the_report_stdout(committed_bytes, rendered_bytes):
    assert len(committed_bytes) == len(rendered_bytes), (
        "REGISTER.md is "
        f"{len(committed_bytes)} B but `report` renders {len(rendered_bytes)} B"
    )
    assert committed_bytes == rendered_bytes, "REGISTER.md drifted from the rendered register"


def test_b1_equality_is_not_vacuous(committed_bytes):
    assert len(committed_bytes) > 10_000, (
        f"the artifact is only {len(committed_bytes)} B, too small to be the ranked register"
    )


def test_b1_no_header_footer_or_provenance_banner_was_added(committed_bytes, rendered_bytes):
    committed_lines = committed_bytes.decode("utf-8").splitlines()
    rendered_lines = rendered_bytes.decode("utf-8").splitlines()
    assert committed_lines[0] == rendered_lines[0], "the artifact has an added header line"
    assert committed_lines[-1] == rendered_lines[-1], "the artifact has an added footer line"
    head = "\n".join(committed_lines[:5]).lower()
    tail = "\n".join(committed_lines[-5:]).lower()
    for phrase in BANNER_PHRASES:
        assert phrase not in head, f"provenance banner {phrase!r} in the artifact's head"
        assert phrase not in tail, f"provenance banner {phrase!r} in the artifact's tail"


# --------------------------------------------------------------------------------------
# Behavior 2 -- exactly one trailing newline.
# --------------------------------------------------------------------------------------


def test_b2_the_artifact_ends_in_exactly_one_newline(committed_bytes):
    assert committed_bytes.endswith(b"\n"), "REGISTER.md does not end with a newline"
    assert not committed_bytes.endswith(b"\n\n"), "REGISTER.md ends with a blank line"
    assert committed_bytes.rstrip(b"\n") + b"\n" == committed_bytes, (
        "REGISTER.md carries more than one trailing newline"
    )


def test_b2_the_renderer_it_mirrors_has_the_same_property(rendered_bytes):
    assert rendered_bytes.endswith(b"\n")
    assert not rendered_bytes.endswith(b"\n\n")


# --------------------------------------------------------------------------------------
# Behavior 3 -- the door is green and silent from ANY working directory.
# --------------------------------------------------------------------------------------


@pytest.mark.parametrize("arm", ["repo_root", "neutral_cwd", "poisoned_cwd"])
def test_b3_the_door_exits_zero_and_is_silent_from_any_cwd(green_arms, arm):
    (rc, out, err), cwd = green_arms[arm]
    assert rc == 0, (
        f"the door exited {rc} with cwd={arm}; stderr was: {err.decode('utf-8', 'replace')!r}"
    )
    assert out == b"", f"the door wrote {len(out)} B to stdout with cwd={arm}: {out[:200]!r}"
    assert err == b"", f"the door wrote {len(err)} B to stderr with cwd={arm}: {err[:400]!r}"
    assert cwd.exists()


def test_b3_the_poisoned_cwd_arm_really_was_poisoned(green_arms):
    """The cwd-independence arm only means something if the decoy exists and differs."""
    _, poisoned = green_arms["poisoned_cwd"]
    decoy = poisoned / "REGISTER.md"
    assert decoy.is_file(), "the decoy REGISTER.md was never written"
    assert decoy.read_bytes() != ARTIFACT.read_bytes(), "the decoy is not actually wrong"


# --------------------------------------------------------------------------------------
# Behavior 4 -- `--file` at a stale copy refuses with exactly one actionable line.
# --------------------------------------------------------------------------------------


@pytest.mark.parametrize(
    "arm", ["appended_newline", "flipped_byte", "truncated", "emptied"]
)
def test_b4_a_stale_copy_is_refused_with_exit_two_and_a_clean_stdout(drift_arms, arm):
    (rc, out, err), copy, _ = drift_arms[arm]
    assert rc == 2, f"{arm}: the door exited {rc}, not 2"
    assert out == b"", f"{arm}: the door wrote {len(out)} B to stdout: {out[:200]!r}"
    line = _sole_stderr_line(err, arm)
    assert str(copy) in line, f"{arm}: the refusal does not name the file it read: {line!r}"
    assert REGEN_COMMAND in line, (
        f"{arm}: the refusal omits the verbatim regeneration command: {line!r}"
    )


def test_b4_a_single_appended_newline_is_enough_to_refuse(drift_arms, committed_bytes):
    (rc, _, _), _, data = drift_arms["appended_newline"]
    assert data == committed_bytes + b"\n"
    assert rc == 2, "one appended newline did not trip the door"


def test_b4_a_length_preserving_flip_is_enough_to_refuse(drift_arms, committed_bytes):
    """Separates a byte comparison from a length comparison: both counts are equal here."""
    (rc, _, err), _, data = drift_arms["flipped_byte"]
    assert len(data) == len(committed_bytes), "the flip arm changed the length"
    assert data != committed_bytes, "the flip arm did not change a byte"
    assert rc == 2, "a single flipped byte at an unchanged length did not trip the door"
    line = err.decode("utf-8")
    assert f"committed {len(data)} B" in line and f"rendered {len(data)} B" in line, (
        f"the refusal did not report two EQUAL byte counts for the flip arm: {line!r}"
    )


def test_b4_a_byte_identical_copy_is_accepted_through_the_same_flag(drift_arms):
    """The refusals above are caused by the DRIFT, not by passing `--file` at all."""
    (rc, out, err), _, _ = drift_arms["identical_control"]
    assert rc == 0, f"a byte-identical copy was refused with exit {rc}: {err!r}"
    assert out == b"" and err == b"", "a byte-identical copy was not accepted silently"


def test_b4_a_missing_file_also_refuses_with_one_actionable_line(tmp_path):
    rc, out, err = _run_door("--file", str(tmp_path / "absent.md"), cwd=tmp_path)
    assert rc == 2, f"a missing artifact exited {rc}, not 2"
    assert out == b"", f"a missing artifact wrote {len(out)} B to stdout"
    line = _sole_stderr_line(err, "missing")
    assert REGEN_COMMAND in line, f"the missing-file refusal omits the recipe: {line!r}"


# --------------------------------------------------------------------------------------
# Behavior 5 -- the refusal states the drift as a DERIVED measurement, not a boolean.
# --------------------------------------------------------------------------------------


@pytest.mark.parametrize(
    "arm", ["appended_newline", "flipped_byte", "truncated", "emptied"]
)
def test_b5_the_refusal_carries_both_measured_byte_counts(drift_arms, arm, rendered_bytes):
    (_, _, err), _, data = drift_arms[arm]
    line = err.decode("utf-8")
    assert f"committed {len(data)} B" in line, (
        f"{arm}: expected 'committed {len(data)} B' in: {line!r}"
    )
    assert f"rendered {len(rendered_bytes)} B" in line, (
        f"{arm}: expected 'rendered {len(rendered_bytes)} B' in: {line!r}"
    )


def test_b5_the_two_counts_move_with_the_input_so_they_are_measured(drift_arms):
    """A boolean dressed up as a number would print the same pair for every arm."""
    pairs = {}
    for arm in ("appended_newline", "truncated", "emptied", "flipped_byte"):
        (_, _, err), _, _ = drift_arms[arm]
        found = re.search(r"committed (\d+) B, rendered (\d+) B", err.decode("utf-8"))
        assert found, f"{arm}: no 'committed N B, rendered N B' measurement: {err!r}"
        pairs[arm] = (int(found.group(1)), int(found.group(2)))
    committed_counts = {pair[0] for pair in pairs.values()}
    assert len(committed_counts) == 4, (
        f"the committed count did not vary across four different inputs: {pairs}"
    )
    rendered_counts = {pair[1] for pair in pairs.values()}
    assert len(rendered_counts) == 1, (
        f"the rendered count changed between arms of one tree: {pairs}"
    )
    assert pairs["flipped_byte"][0] == pairs["flipped_byte"][1], (
        f"the length-preserving arm did not report two equal counts: {pairs}"
    )


def test_b5_neither_byte_count_is_written_down_in_the_door(committed_bytes):
    """`pm.md` behavior 5: the numbers are derived, so the door hardcodes neither."""
    door_text = DOOR.read_text(encoding="utf-8")
    forbidden = str(len(committed_bytes))
    assert forbidden not in door_text, (
        f"the door hardcodes the byte count {forbidden!r} instead of measuring it"
    )


def test_b5_the_door_spells_no_hand_written_locator_dialect():
    """Acceptance criterion: no `startswith("http` dialect anywhere under `tools/`."""
    for path in sorted((REPO_ROOT / "tools").glob("*.py")):
        text = path.read_text(encoding="utf-8")
        assert 'startswith("http' not in text, f"{path.name} spells the locator dialect"
        assert "startswith('http" not in text, f"{path.name} spells the locator dialect"


# --------------------------------------------------------------------------------------
# Behavior 6 -- the README tells a reader the artifact is generated and how to regenerate.
# --------------------------------------------------------------------------------------


def test_b6_the_readme_names_the_artifact_and_carries_the_verbatim_recipe():
    text = README.read_text(encoding="utf-8")
    assert "REGISTER.md" in text, "README.md never names REGISTER.md"
    assert REGEN_COMMAND in text, (
        f"README.md does not carry the verbatim command {REGEN_COMMAND!r}"
    )


def test_b6_the_readme_says_it_is_generated_and_must_not_be_hand_edited():
    lines = [
        line for line in README.read_text(encoding="utf-8").splitlines()
        if "REGISTER.md" in line
    ]
    assert lines, "README.md never names REGISTER.md"
    blob = "\n".join(lines).lower()
    assert "generated" in blob, "README.md does not say REGISTER.md is generated"
    assert re.search(r"hand-edit|hand edit|by hand|edit it by", blob), (
        f"README.md does not warn against hand-editing REGISTER.md: {lines!r}"
    )


# --------------------------------------------------------------------------------------
# Public-repo hygiene for this module's own additions.
# --------------------------------------------------------------------------------------


def test_meta_this_module_writes_down_no_absolute_machine_path():
    text = pathlib.Path(__file__).read_text(encoding="utf-8")
    # Assembled from fragments so the needles themselves are not absolute-path literals.
    needles = ("/" + "Users/", "/" + "home/", "C:" + chr(92))
    for needle in needles:
        assert needle not in text, f"this module writes down an absolute path: {needle!r}"
# --------------------------------------------------------------------------------------
# Behavior 1, extended -- the PUBLISHED route, determinism, and an older committed golden.
# --------------------------------------------------------------------------------------


def test_b1_the_published_recipe_argv_reproduces_the_artifact(monkeypatch, committed_bytes):
    """Acceptance criterion: the artifact was produced by the PUBLISHED command.

    `README.md` and the door's own refusal both spell `radar report . > REGISTER.md`, whose
    argv tail is `("report", ".")` evaluated with the repo root as the cwd -- a DIFFERENT
    route into the register than behavior 1's absolute `<repo root>`. If only the absolute
    form matched, the recipe a reader is handed would not rebuild the file it names.
    """
    monkeypatch.chdir(REPO_ROOT)
    buffer = io.StringIO()
    with contextlib.redirect_stdout(buffer):
        rc = main(["report", "."])
    assert rc == 0, f"the published recipe exited {rc}, not 0"
    assert buffer.getvalue().encode("utf-8") == committed_bytes, (
        "`report .` from the repo root does not reproduce REGISTER.md byte for byte"
    )


def test_b1_the_render_this_artifact_pins_is_byte_stable_across_two_calls(rendered_bytes):
    """A golden of a non-deterministic renderer is a scheduled false alarm, not a brake."""
    buffer = io.StringIO()
    with contextlib.redirect_stdout(buffer):
        rc = main(list(RENDER_ARGV))
    assert rc == 0, f"the second render exited {rc}, not 0"
    assert buffer.getvalue().encode("utf-8") == rendered_bytes, (
        "two renders of one unchanged tree disagree, so no golden of it can be stable"
    )


def test_b1_the_artifact_agrees_with_the_report_golden_pinned_before_iteration_218(
    committed_bytes,
):
    """Independent corroboration that these bytes are not a fresh re-baseline.

    `tests/_iter218_report_golden.py` pinned `report`'s LENGTH and sha256 at a commit dozens
    of iterations before this one. Matching today's renderer proves the artifact is current;
    matching that older digest too proves the document it freezes is the same document the
    repo has been promising all along. Hard import, per the convention iteration 220 set.
    """
    import _iter218_report_golden as report_golden

    expected_len, expected_sha = report_golden.PRECHANGE_DOCUMENTS[("report", "gaps")]
    assert len(committed_bytes) == expected_len, (
        f"REGISTER.md is {len(committed_bytes)} B but the pinned report golden is "
        f"{expected_len} B"
    )
    assert hashlib.sha256(committed_bytes).hexdigest() == expected_sha, (
        "REGISTER.md's sha256 does not match the pinned report golden"
    )


# --------------------------------------------------------------------------------------
# Behavior 3, extended -- "never from the cwd" also excludes asking git at the cwd.
# --------------------------------------------------------------------------------------


@pytest.fixture(scope="module")
def git_repo_cwd(tmp_path_factory):
    """An unrelated git repository holding a decoy `REGISTER.md` and no register at all."""
    directory = tmp_path_factory.mktemp("git_repo_cwd")
    init = subprocess.run(
        ["git", "init", "-q"], cwd=str(directory), capture_output=True
    )
    (directory / "REGISTER.md").write_bytes(b"# a decoy register in another repo\n")
    return init.returncode, directory


def test_b3_the_door_ignores_a_git_repository_at_the_cwd(git_repo_cwd):
    """The poisoned plain directory cannot catch a door that resolves its root via git.

    `git rev-parse --show-toplevel` from a plain tmp directory walks UP and can still find a
    real repo, so that arm would pass for the wrong reason; inside a fresh repo of its own it
    returns that decoy, where no `gaps/` register exists. Only this arm separates the two.
    """
    init_rc, directory = git_repo_cwd
    if init_rc != 0:
        pytest.skip("git init is unavailable in this environment")
    assert (directory / ".git").is_dir(), "the decoy repository was never initialised"
    rc, out, err = _run_door(cwd=directory)
    assert rc == 0, f"the door exited {rc} inside an unrelated git repo: {err[:400]!r}"
    assert out == b"", f"the door wrote {len(out)} B to stdout inside an unrelated repo"
    assert err == b"", f"the door wrote {len(err)} B to stderr inside an unrelated repo"


# --------------------------------------------------------------------------------------
# Behaviors 4-5, extended -- a byte comparison survives bytes no decoder accepts.
# --------------------------------------------------------------------------------------


def test_b4_a_copy_holding_invalid_utf8_is_refused_rather_than_crashed(
    tmp_path, committed_bytes, rendered_bytes
):
    """A text comparison raises `UnicodeDecodeError` here: exit 1 and a multi-line traceback.

    Behavior 4 promises exit 2, zero stdout and EXACTLY ONE `Error: ` line for any changed
    byte, and iterations 258-259 spent two ships on undecodable input reaching a renderer, so
    the arm belongs in this module rather than being assumed from the four clean mutations.
    """
    copy = tmp_path / "invalid_utf8.md"
    payload = b"\xff\xfe" + committed_bytes
    copy.write_bytes(payload)
    rc, out, err = _run_door("--file", str(copy), cwd=tmp_path)
    assert rc == 2, f"an undecodable copy exited {rc}, not 2: {err[:400]!r}"
    assert out == b"", f"an undecodable copy wrote {len(out)} B to stdout: {out[:200]!r}"
    line = _sole_stderr_line(err, "invalid_utf8")
    assert str(copy) in line, f"the refusal does not name the file it read: {line!r}"
    assert REGEN_COMMAND in line, f"the refusal omits the regeneration command: {line!r}"
    assert f"committed {len(payload)} B" in line, (
        f"the refusal did not measure the undecodable copy's length: {line!r}"
    )
    assert f"rendered {len(rendered_bytes)} B" in line, (
        f"the refusal did not report the rendered length: {line!r}"
    )


# --------------------------------------------------------------------------------------
# Public-repo hygiene for the ARTIFACT itself (it is now shippable, tracked bytes).
# --------------------------------------------------------------------------------------


def test_meta_the_committed_artifact_writes_down_no_absolute_machine_path(committed_bytes):
    text = committed_bytes.decode("utf-8")
    # Assembled from fragments so the needles themselves are not absolute-path literals.
    needles = ("/" + "Users/", "/" + "home/", "C:" + chr(92))
    for needle in needles:
        assert needle not in text, (
            f"REGISTER.md carries an absolute machine path: {needle!r}"
        )
